name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.401'
    - uses: actions/checkout@v2
    - name: Build Native.lib
      run: |
        MSBuild .\NativeWrapper\Native.vcxproj /property:Configuration=Debug /property:Platform=x64
        Copy-Item ".\NativeWrapper\x64\Debug\Native.lib" -Destination ".\cor_profiler"
    - name: Build
      run: |
        cargo build --manifest-path .\cor_profiler\Cargo.toml --verbose
        Copy-Item ".\NativeWrapper\x64\Debug\Native.dll" -Destination ".\cor_profiler\target\debug"
    - name: Build SampleLibrary
      run: dotnet build ".\examples\SampleLibrary\SampleLibrary.sln"
    - name: Run tests
      run: |
        Get-ChildItem "C:\Windows\Microsoft.NET\Framework"
        Get-ChildItem "C:\Program Files\dotnet\shared\Microsoft.NETCore.App"
        cargo test --verbose --manifest-path .\cor_profiler\Cargo.toml -- --nocapture --test-threads=1
    
