name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
    - uses: actions/checkout@v2
    - name: Build Native.lib
      run: |
        MSBuild .\NativeWrapper\Native.vcxproj /property:Configuration=Debug /property:Platform=x64
        Copy-Item ".\NativeWrapper\x64\Debug\Native.lib" -Destination ".\cor_profiler"
    - name: Build
      run: cargo build --manifest-path .\cor_profiler\Cargo.toml --verbose
    
